### ISSUE TITLE
How can I predict survival time in real numbers using publicly available code?

### ISSUE THREAD

**Issue by abebe9849** [oeminaga/AI_PCA_GRADE#3]
Thank you for publishing such a great repository! It looks like the model returns a binary of whether the event has occurred or not.
I am new to survival time analysis, so I would like to know how I can predict survival time T from feature quantity X using this model.

**Comment by oeminaga** [comment]
Thank you for your comment. The prediction score is a risk score for BCR that demonstrated good calibration for the tenth year. So, it's interpretable as it correlates with the survival probability (we have more information from this score in contrast to a simple binary prediction where the inaccurate confidence score is enough), allowing stratification with distinct risk groups. The trick is the training set, where we included two extremes reflecting cancer biology and assumed that AI would figure out the gaps between these extremes that would correspond to survival. Since PCa cases need to be followed for at least 10 years to derive meaningful survival analyses given its cancer biology, we ensured the success of the model training by having a good calibration at the 10-year survival.

You can construct a table of Kaplan-Meier estimates for the categorized risk groups within the target cohort. It's crucial to note that the cohort's life expectancy varies across populations due to various factors (difficult to generalize), and it should be hospital-, network- or regional-specific in contrast to what is being propagated in the literature. Predicting survival from histology images is an incomplete story, as other cofounders impact survival (e.g., treatment, health economics, TNM stage, PSA, and age). Therefore, the study cohort should be well-defined (mitigating treatment and health economics impact), and other factors must be evaluated (I refer to our paper related to these points). Additionally, you can develop adjusted survival estimations or include them in a nomogram that accounts for multiple factors (preferred due to its transparency and utility).

**Comment by abebe9849** [comment]
Thank you for your reply.　
I will study it some more.
